services:
  # GO APP (Air ile hot-reload)
  app:
    build:
      context: .
    container_name: url-shortener-app
    env_file: .env
    command: [ "air", "-c", "/app/.air.toml" ]
    volumes:
      - ./:/app           # kodu bind-mount
      - gocache:/go/pkg/mod
    ports:
      - "8080:8080"       # Fiber
    depends_on:
      - mongo
      - redis

  mongo:
    image: mongo:7
    ports: ["27017:27017"]
    volumes: [ "mongo_data:/data/db" ]

  redis:
      image: redis:7-alpine
      container_name: url-shortener-redis
      command: [ "redis-server", "--appendonly", "yes" ]
      ports: [ "6379:6379" ]
      volumes:
        - redis_data:/data

# mongodb compass kullandığım için bunu comment-out ettim uygulama yüklemek istemeyenler bunu açabilir
#  mongo-express:
#    image: mongo-express:1.0.2
#    environment:
#      ME_CONFIG_MONGODB_SERVER: mongo
#      ME_CONFIG_BASICAUTH_USERNAME: admin
#      ME_CONFIG_BASICAUTH_PASSWORD: admin
#    ports: ["8090:8081"] 8081 kullanıldığı için 8090 dan bind ettim
#    depends_on: [mongo]

volumes:
  gocache:
  mongo_data:
  redis_data:
